New fields to the User entity.
Roomify/RfA pull request #152
Opened 2017-04-24 13:08 UTC by salvoscala

We should alter the user entity and have these fields:

- First Name
- Last Name
- Phone Number
- Postal Address
- Email

We should also think about an easy way to add billing profiles from the user edit page (reference_dialog?), a page where the user can manage his billing profiles and remove telephone from billing profile.

2017-05-04 08:36 UTC, salvoscala commented
@cecrs, @acrollet could you please review this? The whole tickets of the project (https://github.com/Roomify/RfA/projects/2) have been done here. Sonia has qa'd it (https://roomify.atlassian.net/browse/RD-800) testing the functionality for new bookings, but we should be also sure that everything on existing sites it's going to work properly.

Many, many thanks!

2017-05-04 19:09 UTC, cecrs requested changes
When attempting to update an existing installation:
pulled issue-152
built the distro
ran composer install
ran dbup
when attempting to clear cache/revert features with drush, get the following error: Fatal error: Call to a member function override_option() on null in .../votingapi.views_default.inc on line 21

2017-05-05 15:30 UTC, acrollet commented
Let's go ahead and get the tests passing :)

2017-05-12 14:49 UTC, acrollet approved these changes
@salvoscala CR passes with fixes for these small things :)

2017-05-12 14:49 UTC, acrollet commented on modules/roomify/roomify_accommodation_booking/roomify_accommodation_booking.module
> +    $form['account']['name']['#description'] = t('Using this (or email) the user will be able to access to the site.') . ' ' . $form['account']['name']['#description'];
let's change to "Using this username (or their email) the user will be able to access the site."

2017-05-12 14:49 UTC, acrollet commented on modules/roomify/roomify_system/roomify_system.module
> +      'edit users with role 2',
where does this permission come from? is there any way to use a machine name?

2017-05-12 14:49 UTC, acrollet commented on modules/roomify/roomify_system/roomify_system.module
> +    $rights['roomify_system']['property owner'][] = 'edit users with role ' . $guest_role->rid;
ah-ha! ;)

2017-05-19 13:52 UTC, merged