"textgroup entityform is not allowed" php-warnings on watchdog & drush -- 1.2.2 release
Roomify/RfA pull request #19
Opened 2016-12-19 22:24 UTC by salvoscala

```php
The string entityform:entityform_type:contact:draft_save_text for textgroup entityform is not allowed for translation because of its text  [warning]
format.
The string entityform:entityform_type:contact:submission_text for textgroup entityform is not allowed for translation because of its text  [warning]
format.
The string entityform:entityform_type:contact:instruction_pre for textgroup entityform is not allowed for translation because of its text  [warning]
format.
The string entityform:entityform_type:listing_enquiry:draft_save_text for textgroup entityform is not allowed for translation because of   [warning]
its text format.
The string entityform:entityform_type:listing_enquiry:instruction_pre for textgroup entityform is not allowed for translation because of   [warning]
its text format.
The string entityform:entityform_type:contact:draft_save_text for textgroup entityform is not allowed for translation because of its text  [warning]
format.
The string entityform:entityform_type:contact:submission_text for textgroup entityform is not allowed for translation because of its text  [warning]
format.
The string entityform:entityform_type:contact:instruction_pre for textgroup entityform is not allowed for translation because of its text  [warning]
format.
The string entityform:entityform_type:listing_enquiry:draft_save_text for textgroup entityform is not allowed for translation because of   [warning]
its text format.
The string entityform:entityform_type:listing_enquiry:instruction_pre for textgroup entityform is not allowed for translation because of   [warning]
its text format.
```

Reporting this as per testing of 1.2.2 release https://github.com/Roomify/RfA/releases/tag/1.2.2

2016-12-19 17:36 UTC, acrollet commented
@marcrobinsone thanks for the report! We'll look into this as we're able.

2016-12-19 22:38 UTC, acrollet commented on modules/roomify/roomify_contact/roomify_contact.features.inc
> -      "roles" : { "1" : "1", "2" : "2", "30037204" : 0, "163670334" : 0 },
@salvoscala let's use role names here instead of IDs. thanks! :)

2016-12-20 19:38 UTC, acrollet requested changes
I'd like to remove the role IDs before we release this.

2016-12-27 11:03 UTC, salvoscala commented
@acrollet I think this is the way the form is exported so we've to change the entityform module to import role names. Any thoughts?

2016-12-27 18:50 UTC, acrollet approved these changes

2016-12-27 18:50 UTC, acrollet commented
@salvoscala hmm I spent some time looking, but there's not a clear-cut way to take care of this. Given that we are only actually relying on the anon and authenticated roles, whose IDs should stay fixed, we can do without going down this rabbit hole. ;)

2016-12-27 18:51 UTC, merged