Review PET Templates.
Roomify/RfA pull request #228
Opened 2017-08-03 10:24 UTC by salvoscala

2017-07-28 08:21 UTC, salvoscala commented
Go through each mail template and check informations. We should be sure to provide all the informations the user needs without opening the site.

2017-08-04 09:39 UTC, salvoscala commented
@acrolloet The goal of this task is to update PET templates and give to guests and owners all the informations they need via mail. I've added some tokens and text to templates.

Email are not recreated with a Drupal update. The site owner will receive an email with a link to update pets and he's informed that this action will delete all templates in the site (including translated ones) and recreate them with new layouts.

2017-08-07 15:53 UTC, acrollet requested changes
CR passes pending this review

2017-08-07 15:53 UTC, acrollet commented on modules/roomify/roomify_accommodation_booking/roomify_accommodation_booking.tokens.inc
> +          $return[$original] =
would it make sense to use a template file here?

2017-08-07 15:53 UTC, acrollet commented on modules/roomify/roomify_system/roomify_system.install
> +    we have made some changes to email templates that are sent through your site. We did not udpdate them cause we have to delete all existing templates (including translation) and recreate them with
cause -> because

2017-08-07 15:53 UTC, acrollet commented on modules/roomify/roomify_system/roomify_system.install
> +    If you want to update them visit this ' . l(t('page'), $url) . '
If you wish to update them, please visit this

2017-08-07 15:53 UTC, acrollet commented on modules/roomify/roomify_system/roomify_system.module
> +      '#markup' => t('Hi! We have made some changes to email templates. Clicking here you will delete your templates and import the new ones. Be carefult that this action will also delete your transl
"Please be aware that this action will delete your translated templates!"

2017-08-09 14:10 UTC, merged