Further improve button text based on 'Instant Booking' status
Roomify/RfA pull request #33
Opened 2016-12-29 11:40 UTC by salvoscala

Two tasks:

- [ ] Casa Properties - Remove the unnecessary 'field_st_allow_instant_bookings' from the House Type bundle
- [ ] Locanda Properties - Alter the button text in the 'Property Types details' view (/admin/structure/views/view/property_travel/edit/panel_pane_3) based on the setting in the 'field_st_allow_instant_bookings' field.

2017-01-20 15:37 UTC, cecrs reviewed
looks good!

2017-01-20 15:43 UTC, acrollet requested changes
minor feedback

2017-01-20 15:43 UTC, acrollet commented on modules/roomify/roomify_accommodation_booking/roomify_accommodation_booking.module
> +        if ($type->type == 'home' || (isset($type->field_st_allow_instant_bookings[LANGUAGE_NONE][0]['value']) &&
can we replace the two tests with a single !empty($type->field_st_allow_instant_bookings[LANGUAGE_NONE][0]['value']) ? Also I'm not quite sure what the comment means :)

2017-01-20 15:43 UTC, acrollet commented on modules/roomify/roomify_listing/roomify_listing.fields.inc
> +        'description' => 'Enabling instant bookings means that users will be able to book and pay immediately. Make sure to setup a suitable payment method.',
is this text translatable?

2017-01-20 17:41 UTC, salvoscala commented on modules/roomify/roomify_listing/roomify_listing.fields.inc
> +        'description' => 'Enabling instant bookings means that users will be able to book and pay immediately. Make sure to setup a suitable payment method.',
@acrollet I think the problem is not just here, I tried to create a new boolean field and have the same issue: it's impossible to translate the description.

2017-01-21 09:45 UTC, salvoscala commented on modules/roomify/roomify_listing/roomify_listing.fields.inc
> +        'description' => 'Enabling instant bookings means that users will be able to book and pay immediately. Make sure to setup a suitable payment method.',
@acrollet I added a patch to the Token module to solve this known issue. Now label and descriptions of fields are completely translatable :)

2017-01-23 16:39 UTC, merged