Add descriptions to fields to improve UX.
Roomify/RfA pull request #79
Opened 2017-01-24 17:15 UTC by salvoscala

Fields like Categories or Areas in the blog haven't a description.

![screen shot 2017-01-20 at 10 13 22](https://cloud.githubusercontent.com/assets/6781952/22143153/4b08cf30-def9-11e6-8568-99d62e154f71.png)

We should review all fields and add a description to help users where we need that.

2017-01-26 17:17 UTC, cecrs requested changes
The link in the Location description in "Things to do" is not right

2017-01-26 17:17 UTC, cecrs commented
![screen shot 2017-01-26 at 11 16 22 am](https://cloud.githubusercontent.com/assets/2028066/22342172/041ea8e6-e3b9-11e6-993f-734826b249ea.png)

2017-01-27 14:23 UTC, salvoscala commented
@cecrs I've added a patch for that issue, can you please qa again? thanks!

2017-01-27 14:26 UTC, acrollet approved these changes
CR passes

2017-01-27 15:23 UTC, cecrs approved these changes

2017-01-27 15:39 UTC, merged