Booking information storage improvements.
Roomify/RfA pull request #84
Opened 2017-01-25 14:49 UTC by salvoscala

2017-01-25 15:01 UTC, acrollet approved these changes
Code looks good

2017-01-30 16:32 UTC, cecrs requested changes
/admin/structure/views/view/dashboard_bookings/edit/views_data_export_1

The csv export is looking for the old fields...

We should also probably add back the guest data to the rest of the bookings views (as is already in next arrivals)

2017-01-31 09:25 UTC, salvoscala commented
@cecrs I've added guest information in views and permissions to manage customer profiles for Managers.

2017-02-01 15:52 UTC, cecrs approved these changes

2017-02-01 16:36 UTC, merged